# Generated by Django 4.0.5 on 2022-07-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الطالب')),
                ('file_no', models.IntegerField(verbose_name='رقم الملف')),
                ('group', models.CharField(max_length=50, verbose_name='المجموعة')),
                ('batch', models.CharField(max_length=50, verbose_name='الدفعة')),
                ('birthdate', models.DateField(verbose_name='تاريخ الميلاد')),
                ('religion', models.CharField(choices=[('مسلم', 'مسلم'), ('مسيحي', 'مسيحي')], default='مسلم', max_length=50, verbose_name='الديانة')),
                ('birthplace', models.CharField(choices=[('الاسكندرية', 'الاسكندرية'), ('البحيرة', 'البحيرة'), ('كفرالشيخ', 'كفرالشيخ'), ('الشرقية', 'الشرقية'), ('الغربية', 'الغربية'), ('الدقهلية', 'الدقهلية'), ('المنوفية', 'المنوفية'), ('القليوبية', 'القليوبية'), ('دمياط', 'دمياط')], default='الاسكندرية', max_length=50, verbose_name='محل الميلاد')),
                ('address', models.CharField(max_length=100, verbose_name='العنوان')),
                ('nationality', models.CharField(default='مصري', max_length=50, verbose_name='الجنسية')),
                ('junior_cert_year', models.IntegerField(verbose_name='سنة اتمام الشهادة الاعدادية')),
                ('junior_cert_total', models.IntegerField(verbose_name='مجموع الشهادة الاعدادية')),
                ('guardian', models.CharField(max_length=50, verbose_name='اسم ولي الامر')),
                ('guardian_rel', models.CharField(max_length=50, verbose_name='صلة قرابة ولي الامر')),
                ('guardian_phone', models.CharField(max_length=50, verbose_name='رقم هاتف ولي الامر')),
                ('national_id', models.CharField(max_length=50, verbose_name='الرقم القومي')),
                ('student_pic', models.ImageField(height_field='200', upload_to='students', verbose_name='صورة الطالب', width_field='200')),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
