# Generated by Django 4.0.5 on 2022-07-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trsana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='junior_cert_year',
            field=models.CharField(max_length=50, verbose_name='سنة اتمام الشهادة الاعدادية'),
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic', models.IntegerField(verbose_name='اللغة العربية')),
                ('math', models.IntegerField(verbose_name='الرياضيات')),
                ('science', models.IntegerField(verbose_name='العلوم')),
                ('social_studies', models.IntegerField(verbose_name='الدراسات الاجتماعية')),
                ('computer', models.IntegerField(verbose_name='الحاسب الالي')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='trsana.student', verbose_name='درجات الطالب')),
            ],
            options={
                'verbose_name': 'درجات الطالب',
                'verbose_name_plural': 'درجات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='CommitteeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_chairman', models.IntegerField(verbose_name='رئيس اللجنة')),
                ('first_member', models.IntegerField(verbose_name='العضو الاول')),
                ('second_member', models.IntegerField(verbose_name='العضو الثاني')),
                ('third_member', models.IntegerField(verbose_name='العضو الثالث')),
                ('forth_member', models.IntegerField(verbose_name='العضو الرابع')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_eval', to='trsana.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقييم اللجنة',
                'verbose_name_plural': 'تقييمات اللجنة',
            },
        ),
    ]
