# Generated by Django 4.0.5 on 2022-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trsana', '0003_alter_student_student_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file_no',
            field=models.IntegerField(unique=True, verbose_name='رقم الملف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(unique=True, upload_to='students', verbose_name='صورة الطالب'),
        ),
    ]
