# Generated by Django 4.0.5 on 2022-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trsana', '0004_alter_student_file_no_alter_student_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم هاتف ولي الامر'),
        ),
    ]
