# Generated by Django 4.0.6 on 2022-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trsana', '0006_student_rel_student_rel_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrades',
            name='spelling',
            field=models.IntegerField(default='1', verbose_name='املاء'),
            preserve_default=False,
        ),
    ]
