# Generated by Django 4.0.6 on 2022-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trsana', '0008_studentgrades_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='junior_cert_place',
            field=models.CharField(max_length=50, null=True, verbose_name='جهة صدور الشهادة الاعدادية'),
        ),
    ]
