# Generated by Django 4.0.6 on 2022-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trsana', '0009_student_junior_cert_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='junior_cert_place',
            field=models.CharField(choices=[('الاسكندرية', 'الاسكندرية'), ('البحيرة', 'البحيرة'), ('كفرالشيخ', 'كفرالشيخ'), ('الشرقية', 'الشرقية'), ('الغربية', 'الغربية'), ('الدقهلية', 'الدقهلية'), ('المنوفية', 'المنوفية'), ('القليوبية', 'القليوبية'), ('دمياط', 'دمياط')], max_length=50, null=True, verbose_name='جهة صدور الشهادة الاعدادية'),
        ),
    ]
