# Generated by Django 4.0.6 on 2022-07-12 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trsana', '0014_alter_student_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='المحرر'),
        ),
    ]
