# Generated by Django 4.0.6 on 2022-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
